name: strophe_example
description: Demonstrates how to use the strophe plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  strophe:
    path: ../
  cupertino_icons: ^1.0.0
  decorated_flutter: ^0.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true